# version: '3.9'
# services:
#   server:
#     image: node
#     container_name: server
#     ports:
#       - '3000:3000'
#     build: .
version: '3.9'

services:
  api:
    build: 
      context: .
      target: production

    ports:
      - 3000:3000
    env_file:
      - ./.env

